aikiwaw/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from aikiblog.views import (TrainingList, StageList, TrainingDetail, UserDetail, DojoList, DojoDetail, NewsList,
                            NewsDetail, TechniqueList, TrainingUpdate, TechTrenUpdate, UserUpdate, month, calendar, add_stage,
                            add_training, add_techniques, add_images, save_user_data, change_avatar)

admin.autodiscover()


urlpatterns = patterns('',
        url(r'^/?$', NewsList.as_view(), name='news-list'),
        url(r'^(?P<page>[0-9]+)/$', NewsList.as_view(), name='news-list'),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^dojo/(?P<slug>[\w\-_]+)/$', DojoDetail.as_view(), name='dojo-detail'),
        url(r'^dojos/$', DojoList.as_view(), name='dojo-list'),
        url(r'^dojos/(?P<page>[0-9]+)/$', DojoList.as_view(), name='dojo-list'),
        url(r'^news/(?P<slug>[\w\-_]+)/$', NewsDetail.as_view(), name='news-detail'),
        url(r'^stages/$', StageList.as_view(), name='stage-list'),
        url(r'^stages/(?P<page>[0-9]+)/$', StageList.as_view(), name='stage-list'),
        url(r'^training/(?P<slug>[\w\-_]+)/$', TrainingDetail.as_view(), name='training-detail'),
        url(r'^training_update/(?P<slug>[\w\-_]+)/$', TrainingUpdate.as_view(), name='training-update'),
        url(r'^technique_update/(?P<slug>[\w\-_]+)/$', TechTrenUpdate.as_view(), name='techtren-update'),
        url(r'^trainings/?$', TrainingList.as_view(), name='training-list'),
        url(r'^trainings/(?P<page>[0-9]+)/$', TrainingList.as_view(), name='training-list'),
        url(r'^technique/(?P<slug>[\w\-_]+)/(?P<page>[0-9]+)/$', TechniqueList.as_view(), name='technique-list'),
        url(r'^technique/(?P<slug>[\w\-_]+)/$', TechniqueList.as_view(), name='technique-list'),
        url(r'^user/(?P<pk>[\w\-_]+)/$', UserDetail.as_view(), name='user-detail'),
        url(r'^user_update/(?P<pk>[\w\-_]+)/$', UserUpdate.as_view(), name='user-update'),
        url(r'^accounts/', include('registration.backends.default.urls')),
        url(r'^add_techniques/$', add_techniques, name='add-techniques'),
        url(r'^add_training/$', add_training, name='add-training'),
        url(r'^add_stage/$', add_stage, name='add-stage'),
        url(r'^add_images/((?P<training_id>[\d]+))/$', add_images, name='add-images'),
        url(r'^save_user_data/(?P<user_id>[\d]+)/$', save_user_data, name='save_user_data'),
        url(r'^change_avatar/((?P<user_id>[\d]+))/$', change_avatar, name='change-avatar'),
        url(r'^calendar/(\d+)/$', calendar, name='calendar'),
        url(r'^calendar/$', calendar, name='calendar'),
        url(r"^calendar/month/(\d+)/(\d+)/(prev|next)/$", month, name='month'),
        url(r"^calendar/month/(\d+)/(\d+)/$", month, name='month'),
        url(r"^calendar/month$", month, name='month'),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aikiblog/models.py
# -*- coding: utf-8 -*-

import os
from cStringIO import StringIO

from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.files.uploadedfile import SimpleUploadedFile

from PIL import Image as ImagePIL


class User(AbstractUser):
    SEX = (
        ('K','Kobieta'),
        ('M','Mężczyzna'),
    )
    avatar = models.ImageField(upload_to='static/avatars/%Y/%m/%d', null=True, blank=True)
    start_year = models.IntegerField(null=True, blank=True, verbose_name='Trenuje od')
    about_text = models.TextField(null=True, blank=True, verbose_name='O mnie')
    sex = models.CharField(max_length=1, choices=SEX, verbose_name='Płeć')

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.id})


class News(models.Model):
    title = models.CharField('Tytuł', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)
    posted_date = models.DateTimeField('Data publikacji')
    image = models.ImageField(upload_to='static/news', null=True, blank=True, verbose_name='Zdjęcie')
    text = models.TextField(null=True, blank=True, verbose_name='Treść')
    author = models.ForeignKey(User, verbose_name='Autor')

    class Meta:
        verbose_name = "News"
        verbose_name_plural = "Newsy"

    def __unicode__(self):
        return self.title


class Sensei(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Sensei"
        verbose_name_plural = "Senseje"

    def __unicode__(self):
        return self.name


class Dojo(models.Model):
    name = models.CharField('Nazwa dojo', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)
    start_year = models.IntegerField(verbose_name='Rok założenia')
    city = models.CharField('Miasto', max_length=50)
    adress = models.CharField('Adres', max_length=50)
    sensei = models.ForeignKey(Sensei, verbose_name='Sensei')
    image1 = models.ImageField(upload_to='static/dojo', verbose_name='Zdjęcie 1')
    image2 = models.ImageField(upload_to='static/dojo', null=True, blank=True, verbose_name='Zdjęcie 2')
    image3 = models.ImageField(upload_to='static/dojo', null=True, blank=True, verbose_name='Zdjęcie 3')
    story = models.TextField(null=True, blank=True, verbose_name='Historia')
    trainings = models.TextField(null=True, blank=True, verbose_name='Treningi')
    users = models.ManyToManyField(User, blank=True, verbose_name='Byli tutaj')

    class Meta:
        verbose_name = "Dojo"
        verbose_name_plural = "Dojo"

    def __unicode__(self):
        return self.name


class Stand(models.Model):
    name = models.CharField('Nazwa postawy', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Postawa"
        verbose_name_plural = "Postawy"

    def __unicode__(self):
        return self.name


class Attack(models.Model):
    name = models.CharField('Nazwa ataku', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Atak"
        verbose_name_plural = "Ataki"

    def __unicode__(self):
        return self.name


class Technique(models.Model):
    name = models.CharField('Nazwa techniki', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Techika"
        verbose_name_plural = "Techniki"

    def __unicode__(self):
        return self.name


class TechTren(models.Model):
    user = models.ForeignKey(User, verbose_name='Ćwiczący')
    date = models.DateField('Data treningu')
    stand = models.ForeignKey(Stand, verbose_name='Postawa')
    attack = models.ForeignKey(Attack, verbose_name='Atak')
    technique = models.ForeignKey(Technique, verbose_name='Technika')
    mistakes = models.TextField(verbose_name='Błędy')
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Techika z treningu"
        verbose_name_plural = "Techniki z treningu"

    def __unicode__(self):
        return self.slug

    def save(self, force_insert=False, force_update=False, using=None):
        self.slug = slugify(str(self.date) + " " + str(self.stand) + " " + str(self.attack) +
                            " " + str(self.technique) + " " + str(self.user_id))
        super(TechTren, self).save(force_insert, force_update, using)

    def get_absolute_url(self):
        self.training = Training.objects.get(techniques=self.id)
        return reverse('training-detail', kwargs={'slug': self.training})


class Training(models.Model):
    TYPE = (
        ('T','trening'),
        ('S','staż'),
    )
    user = models.ForeignKey(User, verbose_name='Ćwiczący', null=True, blank=True)
    date = models.DateTimeField('Data i godzina treningu')
    place = models.ForeignKey(Dojo, verbose_name='Miejsce treningu')
    sensei = models.ForeignKey(Sensei, verbose_name='Sensei')
    slug = models.SlugField('Odnosnik', max_length=50, null=True, blank=True)
    techniques = models.ManyToManyField(TechTren, verbose_name='Techniki')
    type = models.CharField(max_length=1, choices=TYPE, verbose_name='Typ')
    notes = models.TextField(verbose_name="Notatki")

    class Meta:
        verbose_name = "Trening"
        verbose_name_plural = "Treningi"
        ordering = ['-date']

    def __unicode__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('training-detail', kwargs={'slug': self.slug})

    def save(self, force_insert=False, force_update=False, using=None):
        d = self.date
        dt = '{:%Y-%m-%d %H-%M}'.format(d)
        self.slug = slugify(str(self.user) + " " + str(dt) + " " + str(self.place))
        super(Training, self).save(force_insert, force_update, using)


class TrainingComment(models.Model):
    training = models.ForeignKey(Training)
    text = models.CharField(max_length=160, verbose_name='Tekst komentarza')
    posted_date = models.DateTimeField('Data dodania', auto_now_add=True)
    author = models.ForeignKey(User)

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"


class Image(models.Model):
    image = models.ImageField('Zdjęcie', upload_to='static/galleries/%Y/%m/%d')
    thumbnail = models.ImageField(upload_to='static/galleries/thumbnails/%Y/%m/%d', null=True, blank=True)
    training = models.ForeignKey(Training)
    date = models.DateTimeField('Data dodania', auto_now_add=True)
    description = models.CharField(max_length=160, verbose_name='Opis zdjęcia', null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Ćwiczący', null=True, blank=True)

    class Meta:
        verbose_name = "Zdjęcie"
        verbose_name_plural = "Zdjęcia"

    def __unicode__(self):
        return self.training

    def create_thumbnail(self):
        if not self.image:
            return

        THUMBNAIL_SIZE = (100, 75)
        DJANGO_TYPE = self.image.file.content_type

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'
        image = ImagePIL.open(StringIO(self.image.read()))
        image.thumbnail(THUMBNAIL_SIZE, ImagePIL.ANTIALIAS)
        temp_handle = StringIO()
        image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1], temp_handle.read(), content_type=DJANGO_TYPE)
        self.thumbnail.save('%s_thumbnail.%s' % (os.path.splitext(suf.name)[0], FILE_EXTENSION), suf, save=False)

    def save(self, *args, **kwargs):
        self.create_thumbnail()
        force_update = False
        if self.id:
            force_update = True
        super(Image, self).save(force_update=force_update)

aikiblog/forms.py
# -*- coding: utf-8 -*-

import datetime

from django import forms
from django.forms import models
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from PIL import Image as PILImage

from .models import TechTren, TrainingComment, Training, Image, User



CUR_YEAR = datetime.datetime.now().year
START_YEAR_CHOICES = tuple(
    [(year, year) for year in range(CUR_YEAR, CUR_YEAR - 30, -1)])
K = 'K'
M = 'M'
SEX_CHOICES = (
    (K, u'kobieta'),
    (M, u'mężczyzna')
)


def _get_techniques_by_user(user):
    techniques = TechTren.objects.filter(user__id=user.id).order_by('-date')
    choices = []
    for t in techniques:
        choices.append((t.id, t.slug))
    return choices


class UpdateTrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ['date', 'place', 'sensei', 'techniques', 'notes']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'start_year', 'about_text', 'sex', 'avatar']


class AddTrainingForm(UpdateTrainingForm):
    class Meta:
        model = Training
        fields = ['date', 'place', 'sensei', 'techniques', 'notes']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AddTrainingForm, self).__init__(*args, **kwargs)
        if self.request.user.is_authenticated():
            self.fields['techniques'].choices = \
                _get_techniques_by_user(self.request.user)


class AddTechniquesForm(forms.ModelForm):
    class Meta:
        model = TechTren
        fields = ['date', 'stand', 'attack', 'technique', 'mistakes']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AddTechniquesForm, self).__init__(*args, **kwargs)


class SaveUserDataForm(forms.Form):
    first_name = forms.CharField(initial='')
    last_name = forms.CharField(initial='')
    start_year = forms.ChoiceField(choices=START_YEAR_CHOICES, initial=2015)
    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=SEX_CHOICES)
    avatar = forms.ImageField()
    about_me = forms.CharField(widget=forms.Textarea(), required=False, initial='')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)

        super(SaveUserDataForm, self).__init__(*args, **kwargs)

    def save(self, user_id):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        start_year = self.cleaned_data.get('start_year')
        sex = self.cleaned_data.get('sex')
        about_me = self.cleaned_data.get('about_me')
        avatar = self.cleaned_data.get('avatar')
        user = get_user_model().objects.get(id=user_id)
        if user:
            user.first_name = first_name
            user.last_name = last_name
            user.start_year = start_year
            user.sex = K if sex == 'K' else M
            if avatar:
                user.avatar = SimpleUploadedFile(avatar.name, avatar.read(), content_type='image/jpeg')
                user.save()
                im = PILImage.open(str(user.avatar))
                width = im.size[0]
                height = im.size[1]
                size = (300, 300)
                if width > height:
                    lcor = (width - height)/2
                    rcor = width - lcor
                    box = (lcor, 0, rcor, height)
                elif height > width:
                    lcor = (height - width)/2
                    rcor = height - lcor
                    box = (0, lcor, width, rcor)
                else:
                    box = (0, 0, width, width)

            region = im.crop(box)
            region.thumbnail(size)
            region.save(str(user.avatar), "JPEG")

        if about_me:
            user.about_text = about_me

        user.save()


class TrainingCommentForm(forms.ModelForm):

    class Meta:
        model = TrainingComment
        fields = ['training', 'text']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TrainingCommentForm, self).__init__(*args, **kwargs)


class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = "__all__"


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'description']


def get_image_formset(form, formset=models.BaseInlineFormSet, **kwargs):
    return models.inlineformset_factory(Training, Image, form, formset, **kwargs)

aikiblog/templates/add_images.html
{%  extends "base_forms.html" %}
{% block content %}
	<a name="content"></a>
	<form method="post" action="" enctype="multipart/form-data">
	{% csrf_token %}
			Dodaj zdjęcia ze swojego treningu z {{ training.date|date:"d E Y " }}
		o godzinie {{ training.date|date:" H:i " }}  w {{ training.place }}:<br><br>
			<table id="id_contact_info_table" border="0" cellpadding="0" cellspacing="5">
				<thead>
					<tr>
						<th scope="col">Zdjęcie</th>
						<th scope="col"></th>
						<th scope="col">Opis</th>
						<th scope="col">Usuń</th>
					</tr>
				</thead>
				<tbody>
					{% for form in formset.forms %}
					<tr id="{{ form.prefix }}-row">
						<td>
							{% for fld in form.hidden_fields %}
								{{ fld }}
							{% endfor %}
							{% if form.instance.pk %}
								<img src="{{ STATIC_URL|cut:'static/' }}{{ form.instance.thumbnail }}" height="50">
							{% endif %}
						</td>
						<td>{% if form.instance.pk %}
								Zmień:<br>
							{% endif %}
							<input id="{{ form.prefix }}-image" name="{{ form.prefix }}-image" type="file" />
						</td>
						<td>
							{{ form.description }}
						</td>
						<td>{% if form.instance.pk %}
								{{ form.DELETE }}
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			<p>
				{{ formset.management_form }}
				<input type="submit" value="Zapisz" />
			</p>
	</form>
{% endblock %}

aikiblog/templates/add_stage.html
{%  extends "base_forms.html" %}
{% load staticfiles %}
{% block content %}
	<meta http-equiv="Refresh" content="60" />
	<a name="content"></a>
	Dodaj informacje o swoim stażu.<br>
	Techniki zaznaczaj z klawiszem CTRL.<br>
	Jeśli nie dodałeś jeszcze technik z tego treningu, dodaj je za pomocą <a href="{% url "add-techniques" %}#content">
	<u>tego formularza!</u></a>,<br> lub kliknij znak + obok okna wyboru technik<br><br>
<table>
	<form method="post" class="form-horizontal" role="form">
		{% csrf_token %}
		<div class="form-group">
			{% for field in form %}
				{% if field.name == 'techniques' %}
					<tr><td id="form_label">{{ field.label }}:</td>
						<td valign="top">
							<select multiple="multiple" id="id_techniques" name="techniques" size="18">
								{% for technique in techniques %}
									<option value={{ technique.id }}>{{ technique.date|date:"d.m.y" }} - {{ technique.stand.name }} {{ technique.attack.name }} {{ technique.technique.name }}</option>
								{% endfor %}
							</select><td><a onclick="myOpen();" onmouseover=" " style="cursor: pointer;"><b><font size="6">+</font></b></a></td></td>
						<td id="form_errors">{% for error in field.errors %}{{ error }}{% endfor %}</td>
					</tr>
					<tr>
						<td></td>
						<td><a onclick="window.location.reload()" target="_blank" onmouseover=" " style="cursor: pointer;">Odśwież bazę</a></td>
					</tr>
				{% else %}
					<tr>
						<td id="form_label">{{ field.label }}:</td>
						<td>{{ field }}</td>
						<td id="form_errors">{% for error in field.errors %}{{ error }}{% endfor %}</td>
					</tr>
				{% endif %}
			{% endfor %}
		</div>
		<tr>
			<td></td>
			<td>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-default">Zapisz</button>
					</div>
				</div>
			</td>
		</tr>
	</form>
</table>
	<script>
	function myOpen() {
		window.open("{% url "add-techniques" %}#content", null, "height=370, width=550, status=no, toolbar=no, menubar=no, location=no");
	}
	</script>
	<script src="{% static 'js/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			$('#id_place').autocomplete();
			$.datetimepicker.setLocale('pl');
			$('#id_date').datetimepicker({
				step: 15,
				format:'d.m.Y H:i',
				dayOfWeekStart: 1
			});
		});
	</script>
{% endblock %}

aikiblog/templates/add_techniques.html
{%  extends "base_forms.html" %}
{%  load staticfiles %}
{% block content %}

	Dodaj techniki ze swojego treningu lub stażu:<br><br>
	<a name="content"></a>
	<table>
	<form method="post" class="form-horizontal" role="form">
		{% csrf_token %}
				<div class="form-group">
					{% for field in form %}
						<tr>
							<td id="form_label">{{ field.label }}:</td>
							<td>{{ field }}</td>
							<td id="form_errors">{% for error in field.errors %}{{ error }}{% endfor %}</td>
						</tr>
					{% endfor %}
				</div>
		<tr><td></td>
			<td>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-default">Dodaj technikę</button><br><br> lub przejdź do dodawania<br> <a href="{% url "add-training" %}#content">TRENINGU</a>/<a href="{% url "add-stage" %}#content">STAŻU</a>
					</div>
				</div>
			</td>
		</tr>
	</form>
	</table><br><br>
	Twoje wszystkie techniki:<br><br>
	<table>
		<tr>
			<td><b>Data</b></td>
			<td><b>Postawa</b></td>
			<td><b>Atak</b></td>
			<td><b>Technika</b></td>
			<td><b>Błędy</b></td>
		</tr>
		{% for techtren in techtrens %}
		{% ifchanged %}
			<tr><td id="techniques_table_space">{{ techtren.date|date:" d.m.Y " }}</td></tr>
		{% endifchanged %}
		<tr>
			<td>{{ techtren.date|date:" d.m.Y " }}&nbsp;&nbsp;</td>
			<td>{{ techtren.stand }}&nbsp;&nbsp;</td>
			<td>{{ techtren.attack }}&nbsp;&nbsp;</td>
			<td><a href="{% url "technique-list" techtren.technique.slug %}">{{ techtren.technique }}</a>&nbsp;&nbsp;</td>
			<td>{{ techtren.mistakes }}&nbsp;&nbsp;</td>
		</tr>
		{% empty %}
		<tr>
			<td>[puste]&nbsp;&nbsp;</td>
			<td>[puste]&nbsp;&nbsp;</td>
			<td>[puste]&nbsp;&nbsp;</td>
			<td>[puste]&nbsp;&nbsp;</td>
			<td>[puste]&nbsp;&nbsp;</td>
		</tr>
		{% endfor %}
	</table>
	<script src="{% static 'js/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			$.datetimepicker.setLocale('pl');
			$('#id_date').datetimepicker({
				step: 15,
				format:'d.m.Y',
				dayOfWeekStart: 1,
				timepicker: false
			});
		});
	</script>
{% endblock %}

aikiblog/templates/add_training.html
{%  extends "base_forms.html" %}
{% load staticfiles %}
{% block content %}
	<meta http-equiv="Refresh" content="60" />
	<a name="content"></a>
	Dodaj informacje o swoim treningu.<br>
	Techniki zaznaczaj z klawiszem CTRL.<br>
	Jeśli nie dodałeś jeszcze technik z tego treningu, dodaj je za pomocą <a href="{% url "add-techniques" %}#content">
	<u>tego formularza!</u></a>,<br> lub kliknij znak + obok okna wyboru technik<br><br>
<table>
	<form method="post" class="form-horizontal" role="form">
		{% csrf_token %}
		<div class="form-group">
			{% for field in form %}
				{% if field.name == 'techniques' %}
					<tr><td id="form_label">{{ field.label }}:</td>
						<td valign="top">
							<select multiple="multiple" id="id_techniques" name="techniques" size="18">
								{% for technique in techniques %}
									<option value={{ technique.id }}>{{ technique.date|date:"d.m.y" }} - {{ technique.stand.name }} {{ technique.attack.name }} {{ technique.technique.name }}</option>
								{% endfor %}
							</select><td><a onclick="myOpen();" onmouseover=" " style="cursor: pointer;"><b><font size="6">+</font></b></a></td></td>
						<td id="form_errors">{% for error in field.errors %}{{ error }}{% endfor %}</td>
					</tr>
					<tr>
						<td></td>
						<td><a onclick="window.location.reload()" target="_blank" onmouseover=" " style="cursor: pointer;">Odśwież bazę</a></td>
					</tr>
				{% else %}
					<tr>
						<td id="form_label">{{ field.label }}:</td>
						<td>{{ field }}</td>
						<td id="form_errors">{% for error in field.errors %}{{ error }}{% endfor %}</td>
					</tr>
				{% endif %}
			{% endfor %}
		</div>
		<tr>
			<td></td>
			<td>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-default">Zapisz</button>
					</div>
				</div>
			</td>
		</tr>
	</form>
</table>
	<script>
	function myOpen() {
		window.open("{% url "add-techniques" %}#content", null, "height=370, width=550, status=no, toolbar=no, menubar=no, location=no");
	}
	</script>
	<script src="{% static 'js/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			$('#id_place').autocomplete();
			$.datetimepicker.setLocale('pl');
			$('#id_date').datetimepicker({
				step: 15,
				format:'d.m.Y H:i',
				dayOfWeekStart: 1
			});
		});
	</script>
{% endblock %}

aikiblog/templates/change_avatar.html
{% extends "base_forms.html" %}

{% block content %}
Ustaw swój avatar:
	<table>
	<form method="post" action="/change_avatar/{{ user.id }}/" enctype="multipart/form-data">
	{% csrf_token %}
		<tr>
			<td><input id="id_first_name" name="first_name" type="text" value={{ request.user.first_name }} hidden="hidden"></td>
			<td><input id="id_last_name" name="last_name" type="text" value={{ request.user.last_name }} hidden="hidden"></td>
			<td><input id="id_start_year" name="start_year" type="number" value={{ request.user.start_year }} hidden="hidden"></td>
			<td>
				<select id="id_sex" name="sex"  hidden="hidden"><option value={{ request.user.sex }} selected="selected"> </option></select>
			</td>
			<td><textarea cols="40" id="id_about_me" name="about_me" rows="10" hidden="hidden">{{ request.user.about_text }}</textarea></td>
		</tr>
		<tr>
			<td>Teraz:<br><img src="{{ STATIC_URL|cut:'static/' }}{{ request.user.avatar }}" height=200 alt="" class="center" ><br>Zmień:{{ form.avatar }}</td>
			<td id="form_errors" style="vertical-align: bottom">{{ form.avatar.errors }}</td>
		</tr>
		<tr>
			<td><button type="submit" class="btn btn-primary">Zapisz</button></td>
		</tr>
	</form>
	</table>
{% endblock %}