aikiwaw/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from aikiblog.views import (TrainingList, StageList, TrainingDetail, UserDetail, DojoList, DojoDetail, NewsList,
                            NewsDetail, TechniqueList, TrainingUpdate, TechTrenUpdate, UserUpdate, month, calendar, add_stage,
                            add_training, add_techniques, add_images, save_user_data, change_avatar)

admin.autodiscover()


urlpatterns = patterns('',
        url(r'^/?$', NewsList.as_view(), name='news-list'),
        url(r'^(?P<page>[0-9]+)/$', NewsList.as_view(), name='news-list'),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^dojo/(?P<slug>[\w\-_]+)/$', DojoDetail.as_view(), name='dojo-detail'),
        url(r'^dojos/$', DojoList.as_view(), name='dojo-list'),
        url(r'^dojos/(?P<page>[0-9]+)/$', DojoList.as_view(), name='dojo-list'),
        url(r'^news/(?P<slug>[\w\-_]+)/$', NewsDetail.as_view(), name='news-detail'),
        url(r'^stages/$', StageList.as_view(), name='stage-list'),
        url(r'^stages/(?P<page>[0-9]+)/$', StageList.as_view(), name='stage-list'),
        url(r'^training/(?P<slug>[\w\-_]+)/$', TrainingDetail.as_view(), name='training-detail'),
        url(r'^training_update/(?P<slug>[\w\-_]+)/$', TrainingUpdate.as_view(), name='training-update'),
        url(r'^technique_update/(?P<slug>[\w\-_]+)/$', TechTrenUpdate.as_view(), name='techtren-update'),
        url(r'^trainings/?$', TrainingList.as_view(), name='training-list'),
        url(r'^trainings/(?P<page>[0-9]+)/$', TrainingList.as_view(), name='training-list'),
        url(r'^technique/(?P<slug>[\w\-_]+)/(?P<page>[0-9]+)/$', TechniqueList.as_view(), name='technique-list'),
        url(r'^technique/(?P<slug>[\w\-_]+)/$', TechniqueList.as_view(), name='technique-list'),
        url(r'^user/(?P<pk>[\w\-_]+)/$', UserDetail.as_view(), name='user-detail'),
        url(r'^user_update/(?P<pk>[\w\-_]+)/$', UserUpdate.as_view(), name='user-update'),
        url(r'^accounts/', include('registration.backends.default.urls')),
        url(r'^add_techniques/$', add_techniques, name='add-techniques'),
        url(r'^add_training/$', add_training, name='add-training'),
        url(r'^add_stage/$', add_stage, name='add-stage'),
        url(r'^add_images/((?P<training_id>[\d]+))/$', add_images, name='add-images'),
        url(r'^save_user_data/(?P<user_id>[\d]+)/$', save_user_data, name='save_user_data'),
        url(r'^change_avatar/((?P<user_id>[\d]+))/$', change_avatar, name='change-avatar'),
        url(r'^calendar/(\d+)/$', calendar, name='calendar'),
        url(r'^calendar/$', calendar, name='calendar'),
        url(r"^calendar/month/(\d+)/(\d+)/(prev|next)/$", month, name='month'),
        url(r"^calendar/month/(\d+)/(\d+)/$", month, name='month'),
        url(r"^calendar/month$", month, name='month'),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aikiblog/models.py
# -*- coding: utf-8 -*-

import os
from cStringIO import StringIO

from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.files.uploadedfile import SimpleUploadedFile

from PIL import Image as ImagePIL


class User(AbstractUser):
    SEX = (
        ('K','Kobieta'),
        ('M','Mężczyzna'),
    )
    avatar = models.ImageField(upload_to='static/avatars/%Y/%m/%d', null=True, blank=True)
    start_year = models.IntegerField(null=True, blank=True, verbose_name='Trenuje od')
    about_text = models.TextField(null=True, blank=True, verbose_name='O mnie')
    sex = models.CharField(max_length=1, choices=SEX, verbose_name='Płeć')

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.id})


class News(models.Model):
    title = models.CharField('Tytuł', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)
    posted_date = models.DateTimeField('Data publikacji')
    image = models.ImageField(upload_to='static/news', null=True, blank=True, verbose_name='Zdjęcie')
    text = models.TextField(null=True, blank=True, verbose_name='Treść')
    author = models.ForeignKey(User, verbose_name='Autor')

    class Meta:
        verbose_name = "News"
        verbose_name_plural = "Newsy"

    def __unicode__(self):
        return self.title


class Sensei(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Sensei"
        verbose_name_plural = "Senseje"

    def __unicode__(self):
        return self.name


class Dojo(models.Model):
    name = models.CharField('Nazwa dojo', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)
    start_year = models.IntegerField(verbose_name='Rok założenia')
    city = models.CharField('Miasto', max_length=50)
    adress = models.CharField('Adres', max_length=50)
    sensei = models.ForeignKey(Sensei, verbose_name='Sensei')
    image1 = models.ImageField(upload_to='static/dojo', verbose_name='Zdjęcie 1')
    image2 = models.ImageField(upload_to='static/dojo', null=True, blank=True, verbose_name='Zdjęcie 2')
    image3 = models.ImageField(upload_to='static/dojo', null=True, blank=True, verbose_name='Zdjęcie 3')
    story = models.TextField(null=True, blank=True, verbose_name='Historia')
    trainings = models.TextField(null=True, blank=True, verbose_name='Treningi')
    users = models.ManyToManyField(User, blank=True, verbose_name='Byli tutaj')

    class Meta:
        verbose_name = "Dojo"
        verbose_name_plural = "Dojo"

    def __unicode__(self):
        return self.name


class Stand(models.Model):
    name = models.CharField('Nazwa postawy', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Postawa"
        verbose_name_plural = "Postawy"

    def __unicode__(self):
        return self.name


class Attack(models.Model):
    name = models.CharField('Nazwa ataku', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Atak"
        verbose_name_plural = "Ataki"

    def __unicode__(self):
        return self.name


class Technique(models.Model):
    name = models.CharField('Nazwa techniki', max_length=50)
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Techika"
        verbose_name_plural = "Techniki"

    def __unicode__(self):
        return self.name


class TechTren(models.Model):
    user = models.ForeignKey(User, verbose_name='Ćwiczący')
    date = models.DateField('Data treningu')
    stand = models.ForeignKey(Stand, verbose_name='Postawa')
    attack = models.ForeignKey(Attack, verbose_name='Atak')
    technique = models.ForeignKey(Technique, verbose_name='Technika')
    mistakes = models.TextField(verbose_name='Błędy')
    slug = models.SlugField('Odnosnik', max_length=50)

    class Meta:
        verbose_name = "Techika z treningu"
        verbose_name_plural = "Techniki z treningu"

    def __unicode__(self):
        return self.slug

    def save(self, force_insert=False, force_update=False, using=None):
        self.slug = slugify(str(self.date) + " " + str(self.stand) + " " + str(self.attack) +
                            " " + str(self.technique) + " " + str(self.user_id))
        super(TechTren, self).save(force_insert, force_update, using)

    def get_absolute_url(self):
        self.training = Training.objects.get(techniques=self.id)
        return reverse('training-detail', kwargs={'slug': self.training})


class Training(models.Model):
    TYPE = (
        ('T','trening'),
        ('S','staż'),
    )
    user = models.ForeignKey(User, verbose_name='Ćwiczący', null=True, blank=True)
    date = models.DateTimeField('Data i godzina treningu')
    place = models.ForeignKey(Dojo, verbose_name='Miejsce treningu')
    sensei = models.ForeignKey(Sensei, verbose_name='Sensei')
    slug = models.SlugField('Odnosnik', max_length=50, null=True, blank=True)
    techniques = models.ManyToManyField(TechTren, verbose_name='Techniki')
    type = models.CharField(max_length=1, choices=TYPE, verbose_name='Typ')
    notes = models.TextField(verbose_name="Notatki")

    class Meta:
        verbose_name = "Trening"
        verbose_name_plural = "Treningi"
        ordering = ['-date']

    def __unicode__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('training-detail', kwargs={'slug': self.slug})

    def save(self, force_insert=False, force_update=False, using=None):
        d = self.date
        dt = '{:%Y-%m-%d %H-%M}'.format(d)
        self.slug = slugify(str(self.user) + " " + str(dt) + " " + str(self.place))
        super(Training, self).save(force_insert, force_update, using)


class TrainingComment(models.Model):
    training = models.ForeignKey(Training)
    text = models.CharField(max_length=160, verbose_name='Tekst komentarza')
    posted_date = models.DateTimeField('Data dodania', auto_now_add=True)
    author = models.ForeignKey(User)

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"


class Image(models.Model):
    image = models.ImageField('Zdjęcie', upload_to='static/galleries/%Y/%m/%d')
    thumbnail = models.ImageField(upload_to='static/galleries/thumbnails/%Y/%m/%d', null=True, blank=True)
    training = models.ForeignKey(Training)
    date = models.DateTimeField('Data dodania', auto_now_add=True)
    description = models.CharField(max_length=160, verbose_name='Opis zdjęcia', null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Ćwiczący', null=True, blank=True)

    class Meta:
        verbose_name = "Zdjęcie"
        verbose_name_plural = "Zdjęcia"

    def __unicode__(self):
        return self.training

    def create_thumbnail(self):
        if not self.image:
            return

        THUMBNAIL_SIZE = (100, 75)
        DJANGO_TYPE = self.image.file.content_type

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'
        image = ImagePIL.open(StringIO(self.image.read()))
        image.thumbnail(THUMBNAIL_SIZE, ImagePIL.ANTIALIAS)
        temp_handle = StringIO()
        image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1], temp_handle.read(), content_type=DJANGO_TYPE)
        self.thumbnail.save('%s_thumbnail.%s' % (os.path.splitext(suf.name)[0], FILE_EXTENSION), suf, save=False)

    def save(self, *args, **kwargs):
        self.create_thumbnail()
        force_update = False
        if self.id:
            force_update = True
        super(Image, self).save(force_update=force_update)

aikiblog/forms.py
# -*- coding: utf-8 -*-

import datetime

from django import forms
from django.forms import models
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from PIL import Image as PILImage

from .models import TechTren, TrainingComment, Training, Image, User



CUR_YEAR = datetime.datetime.now().year
START_YEAR_CHOICES = tuple(
    [(year, year) for year in range(CUR_YEAR, CUR_YEAR - 30, -1)])
K = 'K'
M = 'M'
SEX_CHOICES = (
    (K, u'kobieta'),
    (M, u'mężczyzna')
)


def _get_techniques_by_user(user):
    techniques = TechTren.objects.filter(user__id=user.id).order_by('-date')
    choices = []
    for t in techniques:
        choices.append((t.id, t.slug))
    return choices


class UpdateTrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ['date', 'place', 'sensei', 'techniques', 'notes']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'start_year', 'about_text', 'sex', 'avatar']


class AddTrainingForm(UpdateTrainingForm):
    class Meta:
        model = Training
        fields = ['date', 'place', 'sensei', 'techniques', 'notes']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AddTrainingForm, self).__init__(*args, **kwargs)
        if self.request.user.is_authenticated():
            self.fields['techniques'].choices = \
                _get_techniques_by_user(self.request.user)


class AddTechniquesForm(forms.ModelForm):
    class Meta:
        model = TechTren
        fields = ['date', 'stand', 'attack', 'technique', 'mistakes']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(AddTechniquesForm, self).__init__(*args, **kwargs)


class SaveUserDataForm(forms.Form):
    first_name = forms.CharField(initial='')
    last_name = forms.CharField(initial='')
    start_year = forms.ChoiceField(choices=START_YEAR_CHOICES, initial=2015)
    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=SEX_CHOICES)
    avatar = forms.ImageField()
    about_me = forms.CharField(widget=forms.Textarea(), required=False, initial='')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)

        super(SaveUserDataForm, self).__init__(*args, **kwargs)

    def save(self, user_id):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        start_year = self.cleaned_data.get('start_year')
        sex = self.cleaned_data.get('sex')
        about_me = self.cleaned_data.get('about_me')
        avatar = self.cleaned_data.get('avatar')
        user = get_user_model().objects.get(id=user_id)
        if user:
            user.first_name = first_name
            user.last_name = last_name
            user.start_year = start_year
            user.sex = K if sex == 'K' else M
            if avatar:
                user.avatar = SimpleUploadedFile(avatar.name, avatar.read(), content_type='image/jpeg')
                user.save()
                im = PILImage.open(str(user.avatar))
                width = im.size[0]
                height = im.size[1]
                size = (300, 300)
                if width > height:
                    lcor = (width - height)/2
                    rcor = width - lcor
                    box = (lcor, 0, rcor, height)
                elif height > width:
                    lcor = (height - width)/2
                    rcor = height - lcor
                    box = (0, lcor, width, rcor)
                else:
                    box = (0, 0, width, width)

            region = im.crop(box)
            region.thumbnail(size)
            region.save(str(user.avatar), "JPEG")

        if about_me:
            user.about_text = about_me

        user.save()


class TrainingCommentForm(forms.ModelForm):

    class Meta:
        model = TrainingComment
        fields = ['training', 'text']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TrainingCommentForm, self).__init__(*args, **kwargs)


class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = "__all__"


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'description']


def get_image_formset(form, formset=models.BaseInlineFormSet, **kwargs):
    return models.inlineformset_factory(Training, Image, form, formset, **kwargs)

aikiblog/templates/aikiblog/dojo_detail.html
{% extends "base.html" %}

{% block content %}

	<div id="post_head_dojo_detail">
		{{ object.name }}<br>
	</div>
	<div id="post_head_dojo_detail2"><br>
		{{ object.city }} - {{ object.adress }}<br>
		Rok założenia: {{ object.start_year }}<br>
		Sensei: {{ object.sensei }}
		<br><br>
	</div>
	<div id="post_body_dojo_detail"><br>
		Treningi:<br>{{ object.trainings }}<br><br>
		Historia dojo:<br>{{ object.story }}<br><br><br>
		Byli tutaj:<br><br>
		{% for entry in object.users.all %}
			<div id="post_body_avatar">
				<a href="{% url "user-detail" entry.id %}"><img src="{{ STATIC_URL|cut:'static/' }}{{ entry.avatar }}" height=40/></a>
			</div>
			<div id="post_body_entry">
				<a href="{% url "user-detail" entry.id %}">{{ entry.first_name }} {{ entry.last_name }}</a><br>
			</div><br><br><br>
		{% endfor %}
	</div>
	<div id="post_body_dojo_detail_images"><br>
		<img src="{{ STATIC_URL|cut:'static/' }}{{ object.image1 }}" width=570 alt="" class="left" /><br>
		<img src="{{ STATIC_URL|cut:'static/' }}{{ object.image2 }}" width=283 alt="" class="left" />
		<img src="{{ STATIC_URL|cut:'static/' }}{{ object.image3 }}" width=283 alt="" class="left" />
	</div>
{% endblock %}

{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}

aikiblog/templates/aikiblog/dojo_list.html
{% extends "base.html" %}
{% block content %}

{% for entry in dojo_list %}
<div id="post">
	<div id="post_avatar">
		<img src="{{ STATIC_URL|cut:'static/' }}{{ entry.image1 }}" width=70 alt="" class="center" />
	</div>
	<div id="post_head_dojo">
		<a href="{% url "dojo-detail" entry.slug %}">{{ entry.name }}</a>
	</div>
	<div id="post_head_dojo2">
		{{ entry.city }}
	</div>
	<div id="post_body">
	</div>
</div>
{% endfor  %}
	<div>
		{% if is_paginated %}
			{% if page_obj.has_next %}
				<p align="right"><a align="right" href="{% url "dojo-list" page_obj.next_page_number %}">starsze--></a></p>
			{% endif %}
			{% if page_obj.has_previous %}
				<p align="left"><a href="{% url "dojo-list" page_obj.previous_page_number %}"><--nowsze</a></p>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}
{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}

aikiblog/templates/aikiblog/news_detail.html
{% extends "base.html" %}
{% block content %}
	<div id="post">
		<div id="post_avatar_news">
			<img src="{{ STATIC_URL|cut:'static/' }}{{ object.image }}" width=150 alt="" class="center" />
		</div>
        <div id="post_head_news">
			{{ object.title }}
		</div>
        <div id="post_head_news2">
			Dodano: {{ object.posted_date|date:"d E Y" }}
		</div>
		<div id="post_body_news_detail">
			<a name="content"></a>
			<p>{{ object.text|linebreaks }}</p><br><br>
			<a href="{% url "user-detail" object.author.id %}"><img src="{{ STATIC_URL|cut:'static/' }}{{ object.author.avatar }}" height=35>
			{{ object.author.first_name }} {{ object.author.last_name }}</a> - {{ object.posted_date|date:"d E Y" }}
			o {{ object.posted_date|date:"H:i" }}
        </div>
</div>

{% endblock %}
{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}

aikiblog/templates/aikiblog/stage_list.html
{% extends "base.html" %}
{% block content %}

{% for entry in stage_list %}
{% include "aikiblog/parts/training_list.html" %}
{% endfor  %}
	<div>
		{% if is_paginated %}
			{% if page_obj.has_next %}
				<p align="right"><a align="right" href="{% url "stage-list" page_obj.next_page_number %}">starsze&gt;&gt;</a></p>
			{% endif %}
			{% if page_obj.has_previous %}
				<p align="left"><a href="{% url "stage-list" page_obj.previous_page_number %}">&lt;&lt;nowsze</a></p>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}

{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}

aikiblog/templates/aikiblog/training_detail.html
{% extends "base.html" %}
{% block content %}
	<a name="content"></a>
	<div id="post">
		<div id="post_avatar">
		<a href="{% url "user-detail" training.user.id %}"><img src="{{ STATIC_URL|cut:'static/' }}{{ training.user.avatar }}" height=100 alt="" class="center" /></a>
		</div>
		<div id="post_head_training_detail">
		<br><a href="{% url "user-detail" training.user.id %}#content">{{ training.user.first_name }} {{ training.user.last_name }}</a>
			{% ifequal training.user.sex "M" %}
			był
			{% endifequal %}
			{% ifequal training.user.sex "K" %}
			była
			{% endifequal %}
			na
			{% ifequal training.type "T" %}
			treningu
			{% endifequal %}
			{% ifequal training.type "S" %}
			stażu
			{% endifequal %}
			<br> {{ training.date }} w {{ training.place }}
			{% ifequal training.user request.user %}
				<br><a href="{% url "training-update" training.slug %}"><font size="2">[edytuj]</font></a>

			{% endifequal %}
		</div>
		<div id="post_body_training_detail"><br>
		<p><b>Sensei:</b> {{ training.sensei }}</p>
		<table>
		<tr>
			<td width="140" id="table_header_cell">Technika&nbsp;&nbsp;&nbsp;</td>
			<td id="table_header_cell">Błędy</td>
		</tr>
	{% for techtren in training.techniques.all %}
		<tr height="60">
			<td valign="top" id="table_stand_cell">{{ techtren.stand.name }}&nbsp;&nbsp;&nbsp;<br> {{ techtren.attack.name }}<br>
				{% if request.user.is_authenticated %}
					<a href="{% url "technique-list" techtren.technique.slug %}">{{ techtren.technique.name }}</a><br>
					{% ifequal request.user training.user  %}
						<a href="{% url "techtren-update" techtren.slug %}"><font size="1">[edytuj]</font></a>&nbsp;&nbsp;&nbsp;<br>
					{% endifequal %}
				{% else %}
				{{ techtren.technique.name }}&nbsp;&nbsp;&nbsp;
				{% endif %}&nbsp;&nbsp;&nbsp;
			</td>
			<td valign="top" id="table_technique_cell">{{ techtren.mistakes }}</td>
		</tr>
	{% endfor %}
		</table>
		<p><b>Notatki:</b></p>
		{{ training.notes }}
		<br><br>
		<a name="comments"></a>
		<p><b>Zdjęcia:</b></p>
		{% for image in training.image_set.all %}
			<a href="{{ STATIC_URL|cut:"static/" }}{{image.image }}" data-lightbox="image" data-title=
			{% if image.description %}
				"{{ image.description }}"
			{% else %}
				"[brak opisu]"
			{% endif %}
			>
			<img src="{{ STATIC_URL|cut:"static/" }}{{image.thumbnail }}" height=60 alt="" data-lightbox="image-1" /></a>
		{% endfor %}
		{% ifequal request.user training.user  %}
			&nbsp;&nbsp;<a href="{%  url 'add-images' training.id %}"><b><font size="5">+</font></b></a>
		{% endifequal %}
		<br><br>
		<a name="comments"></a>
		<p><b>Komentarze:</b></p>
		<table>
			{% for comment in training.trainingcomment_set.all %}
				<tr>
					<td><img src="{{ STATIC_URL|cut:'static/' }}{{ comment.author.avatar }}" height=35></td>
					<td><b>{{ comment.author.first_name }} {{ comment.author.last_name }}</b> {{ comment.text }}<br>
					<font size=1>{{ comment.posted_date|date:"d E Y "}} o {{ comment.posted_date|date:" H:i " }}</font></td>
				</tr>
			{% empty %}
				<tr><td></td>
				<td>Nie dodano jeszcze komentarzy</td>
				</tr>
				<tr>
				<td>&nbsp</td>
				</tr>
			{% endfor %}
			{% if request.user.is_authenticated %}
			<form method="post" class="form-horizontal" role="form">
			{% csrf_token %}
				<tr>
					<td><img src="{{ STATIC_URL|cut:'static/' }}{{ request.user.avatar }}" height=35></td>
					<td>{{ form.text }}&nbsp;<button type="submit" id="add_comment_button" class="btn btn-default">Dodaj</button><input id="id_training" value="{{ training.id }}" name="training" hidden="hidden"/></td>
				</tr>
			</form>
			{% endif %}
		</table>
		</div>
	</div>
{% endblock %}
{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}

aikiblog/templates/aikiblog/user_detail.html
{% extends "base.html" %}

{% block content %}
	<a name="content"></a>
	<div id="post_avatar">
		<img src="{{ STATIC_URL|cut:'static/' }}{{ user.avatar }}" height=100/>
	</div>
	<div id="post_head_user_detail">
		{{ user.first_name }} {{ user.last_name }}<br>
		Trenuje od: {{ user.start_year }}<br>
		{{ user.about_text }}<br>
		{% ifequal request.user user  %}
			<a href="{%  url 'user-update' user.id %}">[edytuj dane]</a><br>
			<a href="{%  url 'change-avatar' user.id %}">[zmień avatar]</a>
		{% endifequal %}
	</div>
	<div id="post_body_user_detail"><br>
		Moje wpisy:<br><br>
		<table>
		{% for entry in user.training_set.all %}
				<tr>
					<td id="post_body_avatar">
						<img src="{{ STATIC_URL|cut:'static/' }}{{ entry.user.avatar }}" height=40/>
					</td>
					<td id="post_body_entry">
						{{ entry.date }}<br>
						<a href="{% url "training-detail" entry.slug %}#content">
						{% ifequal entry.type "T" %}
						trening
						{% endifequal %}
						{% ifequal entry.type "S" %}
						staż
						{% endifequal %}
						w {{ entry.place }}</a>
					</td>
					<td id="post_body_images">
						{% for image in entry.image_set.all %}
							<a href="{{ STATIC_URL|cut:"static/" }}{{image.image }}" data-lightbox="{{ image.training }}" data-title=
							{% if image.description %}
								"{{ image.description }}"
							{% else %}
							"[brak opisu]"
							{% endif %}
							>
							<img src="{{ STATIC_URL|cut:"static/" }}{{image.thumbnail }}" height=36 alt="" data-lightbox="{{ image.training }}" /></a>
						{% endfor %}
						{% ifequal request.user entry.user  %}
						<a href="{%  url 'add-images' entry.id %}"><b><font size="5">+</font></b></a>
						{% endifequal %}
					</td>
				</tr>
		{% endfor %}
		</table>
	</div>
{% endblock %}

{% block menu_right %}
	{% include "aikiblog/parts/menu_right.html" %}
{% endblock %}